<a href="https://colab.research.google.com/github/aditiR2508/Study-of-Tools-for-EDA--NumPy/blob/main/Expt8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 8
# Study of Tools for EDA- NumPy
## Aditi Rathore
## 25070123006
## EnTC A1

In [ ]:
# NumPy--> Numerical Python
## Creates arrays and performs numerical operations, faster than lists

In [6]:
# Importing numpy and forming arrays
import numpy as snake ## generally imported as 'np' however you can use anything

p = snake.array([10, 20, 30, 40])
q = snake.array([[1, 2, 3],[4, 5, 6]])
print(p)
print(q)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [9]:
#Dimension of p
p.ndim

1

In [10]:
# Shape of a-->syntax:(rows, columns)
p.shape

(4,)

In [11]:
# Shape of b
q.shape

(2, 3)

In [12]:
#datatype-->here, 64 is number of bits
p.dtype

dtype('int64')

In [13]:
# Formation of a zero matrix
snake.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Formation of a matrix containing only ones
snake.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Diagonal matrix--> needs to be symmetric hence input only one number
snake.eye((3)) ##matrix size is 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# "ARANGE" function
snake.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
#"linspace" command
snake.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
#Basic operations-->original array does not get modified
a= p + 5
b= p*3
print(a)
print(b)

[15 25 35 45]
[ 30  60  90 120]


In [22]:
#Mean command-->average
snake.mean(p) ##value is 25.0

np.float64(25.0)

In [23]:
#Median command
snake.median(p)  ##here, median also 25.0

##if mean = median then your data does not have any outliers and is perfect however a vast difference in mean and median means an imperfect data
## median is middle value and since here number of elements is even hence value comes out to 25, if it was odd then we would get middle number

np.float64(25.0)

In [24]:
# Max command
snake.max(q)

np.int64(6)

In [25]:
#Min command
snake.min(q)

np.int64(1)

In [27]:
#Sum of array
snake.sum(p)

np.int64(100)